# Use root/examplerootpass as user/password credentials
services:
  mysql_db:
    image: mysql/mysql-server:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'springpass'
    ports:
      - "3306:3306"
    networks:
      - default

  spring:
    build:
      context:  ./todolist
      dockerfile: Dockerfile
    volumes:
      - ./todolist:/app
      - ./todolist/.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    restart: unless-stopped
    depends_on:
      - mysql_db
    networks:
      - default
    

networks:
  default:
    driver: bridge


  
  
