# Use root/examplerootpass as user/password credentials
version: '3.9'

services:
  mysql_db:
    image: 'mysql:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'spring'
      MYSQL_PASSWORD: 'springpass'
    ports:
      - "3306:3306"
    networks:
      - default
    
  spring:
    build: ./todolist
    container_name: spring
    ports:
      - 8080:8080
    restart: unless-stopped
    image: es_107647
    expose:
      - 8080
    depends_on:
      - mysql_db
    networks:
      - default
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/mydb
      SPRING_DATASOURCE_USERNAME: spring
      SPRING_DATASOURCE_PASSWORD: springpass
      

networks:
  default:
    driver: bridge


  
  
