# Use root/examplerootpass as user/password credentials
services:  
  spring:
    build:
      context:  ./todolist
      dockerfile: Dockerfile
    volumes:
      - ./todolist:/app
      - ./todolist/.m2:/root/.m2
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    restart: unless-stopped
    image: backend-es:v10
    environment:
      SPRING_DATASOURCE_URL : ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME : ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD : ${SPRING_DATASOURCE_PASSWORD}
      EXTERNAL_AUTH_TOKEN_URL: ${EXTERNAL_AUTH_TOKEN_URL}
      EXTERNAL_AUTH_CLIENT_CREDENTIALS : ${EXTERNAL_AUTH_CLIENT_CREDENTIALS}
      COGNITO_JWKS_URL : ${COGNITO_JWKS_URL}
    networks:  
      - default
      
  angular:
    build: ./frontend/es_107647
    container_name: angular
    stdin_open: true
    ports:
      - 4200:4200
    expose:
      - 4200
    restart: unless-stopped
    image: frontend-es
    networks:
      - default
    
networks:
  default:
    driver: bridge


  
  
